export const METADATA_KEYS = {
  MODULE: 'shardix:module',
  INJECTABLE: 'shardix:injectable',
  CONTROLLER: 'shardix:controller',
  SLASH_COMMAND: 'shardix:slash_command',
  CONTEXT_MENU: 'shardix:context_menu',
  MESSAGE_COMMAND: 'shardix:message_command',
  BUTTON: 'shardix:button',
  MODAL: 'shardix:modal',
  AUTOCOMPLETE: 'shardix:autocomplete',
  SELECT_MENU: 'shardix:select_menu',
  EVENT: 'shardix:event',
  CRON: 'shardix:cron',
  INTERVAL: 'shardix:interval',
  GUARDS: 'shardix:guards',
  PIPES: 'shardix:pipes',
  INTERCEPTORS: 'shardix:interceptors',
  MIDDLEWARE: 'shardix:middleware',
  PARAM_INJECT: 'shardix:param_inject',
  DEPENDS_ON: 'shardix:depends_on',
} as const;
